# Generated by Django 6.0.3 on 2026-03-08 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('raw_diagram_json', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('ABANDONED', 'Abandonado')], default='IN_PROGRESS', max_length=20)),
                ('captured_variables', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('procedure_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.procedureversion')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frontend_id', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('QUESTION', 'Pregunta (Múltiples opciones)'), ('INSTRUCTION', 'Instrucción (Sólo continuar)'), ('INPUT', 'Solicitud de variable (Ej: Ingrese monto)'), ('ACTION', 'Acción Automatizada (API/Webhook)')], default='QUESTION', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('is_start_node', models.BooleanField(default=False)),
                ('action_config', models.JSONField(blank=True, null=True)),
                ('procedure_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.procedureversion')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('operator', models.CharField(blank=True, max_length=20, null=True)),
                ('expected_value', models.CharField(blank=True, max_length=255, null=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.node')),
                ('procedure_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.procedureversion')),
            ],
        ),
        migrations.CreateModel(
            name='SessionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('captured_input', models.CharField(blank=True, max_length=255, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.node')),
                ('selected_edge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.edge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.proceduresession')),
            ],
        ),
    ]
