# Generated by Django 6.0.3 on 2026-03-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_node_image_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('can_create_flows', models.BooleanField(default=False)),
                ('can_edit_flows', models.BooleanField(default=False)),
                ('can_delete_flows', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_execute_flows', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='node',
            name='image_url',
        ),
        migrations.AddField(
            model_name='node',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='node_images/'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
